"""empty message

Revision ID: 0beb7b2e16f8
Revises: 30d546248304
Create Date: 2018-11-02 18:22:32.337039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beb7b2e16f8'
down_revision = '30d546248304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_time', sa.Column('link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_time', 'link')
    # ### end Alembic commands ###
