"""empty message

Revision ID: 27a42a01de8a
Revises: 9c01e7d24db8
Create Date: 2018-11-02 17:18:52.011737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a42a01de8a'
down_revision = '9c01e7d24db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_time', sa.Column('data', sa.Unicode(length=4000), nullable=True))
    op.add_column('show_time', sa.Column('total_sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_time', 'total_sales')
    op.drop_column('show_time', 'data')
    # ### end Alembic commands ###
