"""empty message

Revision ID: 30d546248304
Revises: b0826d4affba
Create Date: 2018-11-02 18:11:48.312605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d546248304'
down_revision = 'b0826d4affba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_time_link_key', 'show_time', type_='unique')
    op.drop_column('show_time', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_time', sa.Column('link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('show_time_link_key', 'show_time', ['link'])
    # ### end Alembic commands ###
