"""empty message

Revision ID: 3f7f9a3e81d2
Revises: 7363edeee8e3
Create Date: 2018-11-01 22:25:18.797302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7f9a3e81d2'
down_revision = '7363edeee8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chart_pkey')
    )
    # ### end Alembic commands ###
