"""empty message

Revision ID: 7363edeee8e3
Revises: 
Create Date: 2018-11-01 21:25:34.166227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7363edeee8e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Unicode(length=4000), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('show_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_showtime',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('showtime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['showtime_id'], ['show_time.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_showtime')
    op.drop_table('show_time')
    op.drop_table('movie')
    op.drop_table('data')
    op.drop_table('chart')
    # ### end Alembic commands ###
