"""empty message

Revision ID: 9c01e7d24db8
Revises: c17693384750
Create Date: 2018-11-02 17:12:25.440318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c01e7d24db8'
down_revision = 'c17693384750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('link', sa.String(length=100), nullable=True))
    op.add_column('movie', sa.Column('link', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'movie', ['link'])
    op.add_column('show_time', sa.Column('link', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'show_time', ['link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show_time', type_='unique')
    op.drop_column('show_time', 'link')
    op.drop_constraint(None, 'movie', type_='unique')
    op.drop_column('movie', 'link')
    op.drop_column('data', 'link')
    # ### end Alembic commands ###
