"""empty message

Revision ID: aa991605f926
Revises: c29e05185477
Create Date: 2018-11-02 17:49:25.250643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa991605f926'
down_revision = 'c29e05185477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_data')
    op.drop_table('data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('data_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('data', sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
    sa.Column('total_sales', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('show_data',
    sa.Column('showtime_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], name='show_data_data_id_fkey'),
    sa.ForeignKeyConstraint(['showtime_id'], ['show_time.id'], name='show_data_showtime_id_fkey')
    )
    # ### end Alembic commands ###
