"""empty message

Revision ID: bd51c8ed0c45
Revises: aa991605f926
Create Date: 2018-11-02 17:58:08.913273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd51c8ed0c45'
down_revision = 'aa991605f926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_time', sa.Column('food', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_time', 'food')
    # ### end Alembic commands ###
