"""empty message

Revision ID: c17693384750
Revises: 3f7f9a3e81d2
Create Date: 2018-11-01 22:44:05.406010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17693384750'
down_revision = '3f7f9a3e81d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_data',
    sa.Column('showtime_id', sa.Integer(), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ),
    sa.ForeignKeyConstraint(['showtime_id'], ['show_time.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_data')
    # ### end Alembic commands ###
