"""empty message

Revision ID: c29e05185477
Revises: 27a42a01de8a
Create Date: 2018-11-02 17:34:22.241490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29e05185477'
down_revision = '27a42a01de8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_time', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_time', 'title')
    # ### end Alembic commands ###
