"""empty message

Revision ID: fb7cd547da7a
Revises: bd51c8ed0c45
Create Date: 2018-11-02 18:03:24.126600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7cd547da7a'
down_revision = 'bd51c8ed0c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_time', 'food')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_time', sa.Column('food', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
